# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: en # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.
permalink: /blog/:year/:month/:day/:title/

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
url: # the base hostname & protocol for your site, e.g. http://example.com
baseurl: # the subpath of your site, e.g. /blog
title: Alexey Kuleshevich
description: "My personal website"
keywords: 'Haskell,massiv,blog'
author:
  name:
  job_title:
  location:
  email:
  social_links:
    - name: github
      url: https://github.com/lehins
    - name: linkedin
      url: https://www.linkedin.com/in/lehins/
    - name: stackoverflow
      url: https://stackoverflow.com/users/1848029/lehins
home:
  section1: <h1>Alexey Kuleshevich</h1>
  section2: <h2>My personal website</h2>
  section3: >
    <div class="social-links">
      <a class="ico-github btn" href="https://github.com/lehins" title="GitHub Account"></a>
      <a class="ico-linkedin btn" href="https://www.linkedin.com/in/lehins/" title="LinkedIn Profile"></a>
      <a class="ico-keybase btn" href="https://keybase.io/lehins/" title="Keybase"></a>
    </div>
blog:
  cc_license: http://creativecommons.org/licenses/by-sa/4.0/ # A link to CC License of your choice.
  cc_license_image: /assets/images/theme/cc-by-sa.png # An image of your CC License.
  footer_content: “No matter how brilliant you are, if you sit in a sealed room and have fantastic ideas but don't tell anybody, then all you've done is heat up the universe.” - Simon Peyton Jones

disqus:
  shortname: alexey-kuleshevich
  public_key: qZg8q1coWwUrEXRScvdQsYWeIrLIevhIvEsopSw6D37NA3QNeOHDRUZoUwqv4dlq
google_tag_manager: GTM-KKNBL73
addthis_public_id: # AddThis sharing plugin. See http://www.addthis.com/. E.g. ra-53329e27694534j5

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
